name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a recent LTS Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Add .nojekyll file
        # The build command exports to the `out` directory,
        # so the .nojekyll file needs to be in that output directory.
        run: touch ./out/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Deploy the contents of the `out` directory
